### ISSUE TITLE
Installation Error: cannot get working directory

### ISSUE THREAD

**Issue by KevinWhalen** [planetlabs/qgis-planet-plugin#2]
**Expected:** installation without error from QGIS Official Plugin Repository through the QGIS user-interface.

**Reproduce:** Plugins -> Manage and Install Plugins -> All -> Search "planet explorer" and click Install

**Environment:**

* Fedora 31
* QGIS 3.8.3
* Python 3.7

**Error:** The below error occurs on initial installation and on subsequent loads of QGIS.

```
Traceback (most recent call last):
              File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/kwhalen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/__init__.py", line 36, in classFactory
              return PlanetExplorer(iface)
              File "/home/kwhalen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/pe_plugin.py", line 156, in __init__
              readSettings()
              File "/home/kwhalen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs/qgiscommons2/settings.py", line 143, in readSettings
              namespace = _callerName().split(".")[0]
              File "/home/kwhalen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs/qgiscommons2/utils.py", line 7, in _callerName
              stack = inspect.stack()
              File "/usr/lib64/python3.7/inspect.py", line 1513, in stack
              return getouterframes(sys._getframe(1), context)
              File "/usr/lib64/python3.7/inspect.py", line 1490, in getouterframes
              frameinfo = (frame,) + getframeinfo(frame, context)
              File "/usr/lib64/python3.7/inspect.py", line 1460, in getframeinfo
              filename = getsourcefile(frame) or getfile(frame)
              File "/usr/lib64/python3.7/inspect.py", line 696, in getsourcefile
              if getattr(getmodule(object, filename), '__loader__', None) is not None:
              File "/usr/lib64/python3.7/inspect.py", line 725, in getmodule
              file = getabsfile(object, _filename)
              File "/usr/lib64/python3.7/inspect.py", line 709, in getabsfile
              return os.path.normcase(os.path.abspath(_filename))
              File "/usr/lib64/python3.7/posixpath.py", line 383, in abspath
              cwd = os.getcwd()
             FileNotFoundError: [Errno 2] No such file or directory
```

About QGIS:

>     QGIS version 3.8.3-Zanzibar
>     QGIS code branch Release 3.8
>     Compiled against Qt 5.12.5
>     Running against Qt 5.12.5
>     Compiled against GDAL/OGR 2.3.2
>     Running against GDAL/OGR 2.3.2
>     Compiled against GEOS 3.7.1-CAPI-1.11.1
>     Running against GEOS 3.7.1-CAPI-1.11.1 27a5e771
>     PostgreSQL Client Version 11.6
>     SpatiaLite Version 4.3.0a
>     QWT Version 6.1.3
>     QScintilla2 Version 2.11.2
>     Compiled against PROJ 5.2.0
>     Running against PROJ Rel. 5.2.0, September 15th, 2018
>     OS Version Fedora 31 (Thirty One)

**Comment by KevinWhalen** [comment]
Oops, I was running QGIS from a non-existent directory. Still maybe something worth writing a check for (i.e. make sure get current working directory return something), but probably not an issue many people will run into.
